set -g @theme_session_bg "#76946A"
set -g @theme_session_fg "#2d353b"

set -g @theme_normal_bg "#a7c080"
set -g @theme_normal_fg "#2d353b"

set -g @theme_tmux_bg "#e69875"
set -g @theme_tmux_fg "#2d353b"

set -g @theme_tab_normal_bg "#475258"
set -g @theme_tab_normal_fg "#7a8478"

set -g @theme_tab_active_bg "#e67e80"
set -g @theme_tab_active_fg "#2d353b"

set -g @theme_cpu "#dbbc7f"
set -g @theme_ram "#7fbbb3"
set -g @theme_battery "#a7c080"
set -g @theme_datetime "#ddbb23"
