set -g @theme_session "#DCD7BA"

set -g @theme_normal_bg "#98BB6C"
set -g @theme_normal_fg "#1F1F28"

set -g @theme_tmux_bg "#FFA066"
set -g @theme_tmux_fg "#1F1F28"

set -g @theme_tab_normal_bg "#2A2A37"
set -g @theme_tab_normal_fg "#727169"

set -g @theme_tab_active_bg "#C34043"
set -g @theme_tab_active_fg "#1F1F28"

set -g @theme_cpu "#dbbc7f"
set -g @theme_ram "#7fbbb3"
set -g @theme_battery "#a7c080"
set -g @theme_datetime "#7E9CD8"

