set -g @theme_session_bg "#7a88cf"
set -g @theme_session_fg "#1f2335"

set -g @theme_normal_bg "#85B5BA"
set -g @theme_normal_fg "#2d353b"

set -g @theme_tmux_bg "#EA83A5"
set -g @theme_tmux_fg "#2d353b"

set -g @theme_tab_normal_bg "#3b4252"
set -g @theme_tab_normal_fg "#c9c7cd"

set -g @theme_tab_active_bg "#e29eca"
set -g @theme_tab_active_fg "#2d353b"

set -g @theme_cpu "#dbbc7f"
set -g @theme_ram "#7fbbb3"
set -g @theme_battery "#a7c080"
set -g @theme_datetime "#ea83a5"


