set -g @theme_session "#C0CAF5"

set -g @theme_normal_bg "#9ECE6A"
set -g @theme_normal_fg "#383E5A"

set -g @theme_tmux_bg "#C0CAF5"
set -g @theme_tmux_fg "#383E5A"

set -g @theme_tab_normal_bg "default"
set -g @theme_tab_normal_fg "#a9b1d6"

set -g @theme_tab_active_bg "default"
set -g @theme_tab_active_fg "#93ce6a"

set -g @theme_cpu "#7dcfff"
set -g @theme_ram "#73daca"
set -g @theme_battery "#9ece6a"
set -g @theme_datetime "#7aa2f7"


