set -g @theme_session "##C0CAF5"

set -g @theme_normal_bg "##B4DE8D"
set -g @theme_normal_fg "##1A1B26"

set -g @theme_tmux_bg "##C0CAF5"
set -g @theme_tmux_fg "##1A1B26"

set -g @theme_tab_normal_bg "##5A5F8C"
set -g @theme_tab_normal_fg "##B4DE8D"

set -g @theme_tab_active_bg "##B4DE8D"
set -g @theme_tab_active_fg "##566C9C"

set -g @theme_cpu "##7DCFFF"
set -g @theme_ram "##73DACA"
set -g @theme_battery "##9ECE6A"
set -g @theme_datetime "##7AA2F7"


